"""The Hello World LED board: schematic and board layout.

Ten letters on a 3 by 5 LED grid each, one MOSFET channel per letter, an ATtiny1614
driving the channels, USB-C power, a UPDI header, four mounting holes. Every LED has its
own series resistor. Power is a +5V pour on the top layer and a ground pour on the bottom.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from pathlib import Path

from kicad_layer.kicad_libs import load_footprint
from kicad_layer.models import Netlist
from kicad_layer.pcb_writer import BoardBuilder
from kicad_layer.sch_writer import SchematicBuilder

# --------------------------------------------------------------------------------------
# the word
# --------------------------------------------------------------------------------------

# 3 columns x 5 rows, "#" = LED
FONT = {
    "H": ["#.#", "#.#", "###", "#.#", "#.#"],
    "E": ["###", "#..", "##.", "#..", "###"],
    "L": ["#..", "#..", "#..", "#..", "###"],
    "O": [".#.", "#.#", "#.#", "#.#", ".#."],
    "W": ["#.#", "#.#", "#.#", "###", "#.#"],
    "R": ["##.", "#.#", "##.", "#.#", "#.#"],
    "D": ["##.", "#.#", "#.#", "#.#", "##."],
}
WORD = "HELLOWORLD"
WORD_GAP_AFTER = 4  # extra gap after the 5th letter (index 4)


@dataclass
class Letter:
    index: int
    char: str
    net_suffix: str          # LED_H, LED_L1 ...
    cells: list[tuple[int, int]] = field(default_factory=list)   # (col, row)
    led_refs: dict[tuple[int, int], tuple[str, str]] = field(default_factory=dict)  # cell -> (D ref, R ref)
    mcu_pin: str = ""
    side: str = ""           # "left" or "right" of the MCU


def letters() -> list[Letter]:
    out: list[Letter] = []
    seen: dict[str, int] = {}
    for i, ch in enumerate(WORD):
        seen[ch] = seen.get(ch, 0) + 1
        suffix = ch if WORD.count(ch) == 1 else f"{ch}{seen[ch]}"
        cells = [(c, r) for r, row in enumerate(FONT[ch]) for c, v in enumerate(row) if v == "#"]
        out.append(Letter(index=i, char=ch, net_suffix=suffix, cells=cells))
    # MCU pin assignment: the letter nearest the MCU gets the topmost pin on its side.
    left_pins = ["2", "3", "4", "5", "6"]        # PA4 PA5 PA6 PA7 PB3, nearest first
    right_pins = ["13", "12", "11", "9", "8"]    # PA3 PA2 PA1 PB0 PB1, nearest first
    for k, pin in enumerate(left_pins):
        out[4 - k].mcu_pin, out[4 - k].side = pin, "left"
    for k, pin in enumerate(right_pins):
        out[5 + k].mcu_pin, out[5 + k].side = pin, "right"
    return out


def assign_refs(ls: list[Letter]) -> None:
    n = 0
    for L in ls:
        for cell in L.cells:
            n += 1
            L.led_refs[cell] = (f"D{n}", f"R{n}")


LED_COUNT = sum(len(L.cells) for L in letters())

# --------------------------------------------------------------------------------------
# parts
# --------------------------------------------------------------------------------------

FP_LED = ("LED_SMD", "LED_0603_1608Metric")
FP_R = ("Resistor_SMD", "R_0603_1608Metric")
FP_C0603 = ("Capacitor_SMD", "C_0603_1608Metric")
FP_C0805 = ("Capacitor_SMD", "C_0805_2012Metric")
FP_SOT23 = ("Package_TO_SOT_SMD", "SOT-23")
FP_SOIC14 = ("Package_SO", "SOIC-14_3.9x8.7mm_P1.27mm")
FP_USBC = ("Connector_USB", "USB_C_Receptacle_HRO_TYPE-C-31-M-12")
FP_HDR3 = ("Connector_PinHeader_2.54mm", "PinHeader_1x03_P2.54mm_Vertical")
FP_HOLE = ("MountingHole", "MountingHole_3.2mm_M3")

LED_VALUE = "LED red"
R_LED_VALUE = "1k"
R_CC_VALUE = "5.1k"
C_BULK_VALUE = "10uF"
C_DECOUPLE_VALUE = "100nF"

MCU_GPIO_NAME = {
    "2": "PA4", "3": "PA5", "4": "PA6", "5": "PA7", "6": "PB3", "7": "PB2",
    "8": "PB1", "9": "PB0", "10": "UPDI", "11": "PA1", "12": "PA2", "13": "PA3",
}


def fp_id(fp: tuple[str, str]) -> str:
    return f"{fp[0]}:{fp[1]}"


def _close(a: tuple[float, float], b: tuple[float, float], tol: float = 1e-3) -> bool:
    return abs(a[0] - b[0]) < tol and abs(a[1] - b[1]) < tol


# --------------------------------------------------------------------------------------
# schematic
# --------------------------------------------------------------------------------------


def build_schematic(out_path: Path, project_name: str, ls: list[Letter]) -> dict[str, str]:
    """Write the schematic; return {reference: symbol uuid} for the board's path links."""
    sch = SchematicBuilder(
        project_name,
        paper="A3",
        title="HELLO WORLD LED display",
        date="2026-09-04",
        rev="v0.1",
        company="kicad-mcp-layer",
        comments=[f"{LED_COUNT} LEDs, one MOSFET channel per letter, ATtiny1614 controller", "Generated by kicad-mcp-layer"],
    )
    uuids: dict[str, str] = {}

    def keep(p):
        uuids[p.ref] = p.uuid
        return p

    # ---- USB-C power entry (top left) -------------------------------------------
    ux, uy = 45.72, 63.5
    usb = keep(sch.place("Connector", "USB_C_Receptacle_USB2.0_16P", "J1", (ux, uy), footprint=fp_id(FP_USBC), value_text="USB-C 16P", ref_pos=(ux, uy - 27.94), value_pos=(ux, uy + 30.48)))
    vbus = usb.pin("A4")
    cc1 = usb.pin("A5")
    cc2 = usb.pin("B5")
    gnd_pin = usb.pin("A1")
    shield = usb.pin("SH")
    # VBUS -> +5V with a PWR_FLAG on the way
    flag_pt = (vbus[0] + 5.08, vbus[1])
    top_pt = (vbus[0] + 10.16, vbus[1])
    sch.wire(vbus, flag_pt)
    sch.wire(flag_pt, top_pt)
    sch.junction(flag_pt)
    keep(sch.pwr_flag(flag_pt))
    keep(sch.power("+5V", top_pt))
    # CC pull-downs
    cc2_end = (cc2[0] + 5.08, cc2[1])
    sch.wire(cc2, cc2_end)
    r_cc2 = keep(sch.place("Device", "R", "R91", (cc2_end[0], cc2_end[1] + 3.81), value_text=R_CC_VALUE, footprint=fp_id(FP_R), ref_pos=(cc2_end[0] + 2.54, cc2_end[1] + 3.81), value_pos=(cc2_end[0] + 2.54, cc2_end[1] + 6.35)))
    keep(sch.power("GND", r_cc2.pin("2")))
    cc1_end = (cc1[0] + 12.7, cc1[1])
    sch.wire(cc1, cc1_end)
    r_cc1 = keep(sch.place("Device", "R", "R90", (cc1_end[0], cc1_end[1] + 3.81), value_text=R_CC_VALUE, footprint=fp_id(FP_R), ref_pos=(cc1_end[0] + 2.54, cc1_end[1] + 3.81), value_pos=(cc1_end[0] + 2.54, cc1_end[1] + 6.35)))
    keep(sch.power("GND", r_cc1.pin("2")))
    # GND + shield + PWR_FLAG
    g_flag = (gnd_pin[0], gnd_pin[1] + 2.54)
    g_end = (gnd_pin[0], gnd_pin[1] + 5.08)
    sch.wire(gnd_pin, g_flag)
    sch.wire(g_flag, g_end)
    sch.junction(g_flag)
    keep(sch.pwr_flag(g_flag))
    keep(sch.power("GND", g_end))
    sch.wire(shield, (shield[0], g_end[1]))
    sch.wire((shield[0], g_end[1]), g_end)
    sch.junction(g_end)
    # unused USB pins
    for num in ("A6", "A7", "B6", "B7", "A8", "B8"):
        sch.no_connect(usb.pin(num))
    # bulk capacitor
    c1x, c1y = top_pt[0] + 12.7, vbus[1] + 3.81
    c1 = keep(sch.place("Device", "C", "C1", (c1x, c1y), value_text=C_BULK_VALUE, footprint=fp_id(FP_C0805), ref_pos=(c1x + 2.54, c1y - 1.27), value_pos=(c1x + 2.54, c1y + 1.27)))
    keep(sch.power("+5V", c1.pin("1")))
    keep(sch.power("GND", c1.pin("2")))
    sch.text("USB-C power input. CC pull-downs advertise a 5 V sink.", (ux - 15.24, uy - 33.02), size=1.5)

    # ---- MCU (top middle) ---------------------------------------------------------
    mx, my = 152.4, 63.5
    mcu = keep(sch.place("MCU_Microchip_ATtiny", "ATtiny1614-SS", "U1", (mx, my), footprint=fp_id(FP_SOIC14), ref_pos=(mx - 12.7, my - 20.32), value_pos=(mx, my + 20.32)))
    vcc = mcu.pin("1")
    gnd = mcu.pin("14")
    vcc_top = (vcc[0], vcc[1] - 2.54)
    sch.wire(vcc, vcc_top)
    keep(sch.power("+5V", vcc_top))
    gnd_bot = (gnd[0], gnd[1] + 2.54)
    sch.wire(gnd, gnd_bot)
    keep(sch.power("GND", gnd_bot))
    c2x, c2y = mx - 25.4, my - 15.24
    c2 = keep(sch.place("Device", "C", "C2", (c2x, c2y), value_text=C_DECOUPLE_VALUE, footprint=fp_id(FP_C0603), ref_pos=(c2x + 2.54, c2y - 1.27), value_pos=(c2x + 2.54, c2y + 1.27)))
    keep(sch.power("+5V", c2.pin("1")))
    keep(sch.power("GND", c2.pin("2")))
    for L in ls:
        p = mcu.pin(L.mcu_pin)
        if L.side == "left":
            end = (p[0] - 2.54, p[1])
            sch.wire(p, end)
            sch.label(f"G_{L.net_suffix}", end, rot=180)
        else:
            end = (p[0] + 2.54, p[1])
            sch.wire(p, end)
            sch.label(f"G_{L.net_suffix}", end, rot=0)
    updi = mcu.pin("10")
    updi_end = (updi[0] + 2.54, updi[1])
    sch.wire(updi, updi_end)
    sch.label("UPDI", updi_end, rot=0)
    sch.no_connect(mcu.pin("7"))
    sch.text("ATtiny1614: one GPIO per letter, UPDI programming.", (mx - 22.86, my - 25.4), size=1.5)

    # ---- UPDI header ---------------------------------------------------------------
    hx, hy = mx + 45.72, my
    hdr = keep(sch.place("Connector_Generic", "Conn_01x03", "J2", (hx, hy), value_text="UPDI", footprint=fp_id(FP_HDR3), ref_pos=(hx + 2.54, hy - 5.08), value_pos=(hx + 2.54, hy + 5.08)))
    p1, p2, p3 = hdr.pin("1"), hdr.pin("2"), hdr.pin("3")
    corner1 = (p1[0] - 2.54, p1[1])
    top1 = (corner1[0], corner1[1] - 2.54)
    sch.wire(p1, corner1)
    sch.wire(corner1, top1)
    keep(sch.power("+5V", top1))
    l2 = (p2[0] - 2.54, p2[1])
    sch.wire(p2, l2)
    sch.label("UPDI", l2, rot=180)
    corner3 = (p3[0] - 2.54, p3[1])
    bot3 = (corner3[0], corner3[1] + 2.54)
    sch.wire(p3, corner3)
    sch.wire(corner3, bot3)
    keep(sch.power("GND", bot3))

    # ---- mounting holes -------------------------------------------------------------
    for i in range(4):
        hxh, hyh = 45.72 + 15.24 * i, 120.65
        keep(sch.place("Mechanical", "MountingHole", f"H{i + 1}", (hxh, hyh), footprint=fp_id(FP_HOLE), value_text="M3", ref_pos=(hxh, hyh - 3.81), value_pos=(hxh, hyh + 3.81)))
    sch.text("Mounting holes", (45.72 - 5.08, 120.65 - 6.35), size=1.5)

    # ---- letter drivers and LED blocks ----------------------------------------------
    block_pitch = 30.48
    bx0 = 30.48
    qy = 149.86
    by = 175.26
    for L in ls:
        bx = bx0 + block_pitch * L.index
        qx = bx + 7.62
        q = keep(sch.place("Transistor_FET", "2N7002", f"Q{L.index + 1}", (qx, qy), footprint=fp_id(FP_SOT23), ref_pos=(qx + 6.35, qy - 1.27), value_pos=(qx + 6.35, qy + 1.27)))
        g, s, d = q.pin("1"), q.pin("2"), q.pin("3")
        g_end = (g[0] - 2.54, g[1])
        sch.wire(g, g_end)
        sch.label(f"G_{L.net_suffix}", g_end, rot=180)
        d_end = (d[0], d[1] - 2.54)
        sch.wire(d, d_end)
        sch.label(f"LED_{L.net_suffix}", d_end, rot=90)
        s_end = (s[0], s[1] + 2.54)
        sch.wire(s, s_end)
        keep(sch.power("GND", s_end))

        sch.text(f"{L.char}  ({len(L.cells)} LEDs)", (bx, by - 6.35), size=2.0)
        rail_x = bx
        bus_x = bx + 15.24
        n = len(L.cells)
        rows = [by + 5.08 * i for i in range(n)]
        for i, cell in enumerate(L.cells):
            y = rows[i]
            dref, rref = L.led_refs[cell]
            led = keep(sch.place("Device", "LED", dref, (rail_x + 3.81, y), rot=180, value_text=LED_VALUE, footprint=fp_id(FP_LED), ref_pos=(rail_x + 3.81, y - 2.54), value_pos=(rail_x + 3.81, y + 2.54), hide_value=True, text_size=1.0))
            res = keep(sch.place("Device", "R", rref, (rail_x + 11.43, y), rot=90, value_text=R_LED_VALUE, footprint=fp_id(FP_R), ref_pos=(rail_x + 11.43, y - 2.54), value_pos=(rail_x + 11.43, y + 2.54), hide_value=True, text_size=1.0))
            assert _close(led.pin("2"), (rail_x, y)), led.pin("2")
            assert _close(led.pin("1"), res.pin("1")), (led.pin("1"), res.pin("1"))
            assert _close(res.pin("2"), (bus_x, y)), res.pin("2")
        # +5V rail
        rail_top = (rail_x, rows[0] - 2.54)
        keep(sch.power("+5V", rail_top))
        sch.wire(rail_top, (rail_x, rows[0]))
        for a, b in zip(rows, rows[1:]):
            sch.wire((rail_x, a), (rail_x, b))
        for y in rows[:-1]:
            sch.junction((rail_x, y))
        # letter bus
        for a, b in zip(rows, rows[1:]):
            sch.wire((bus_x, a), (bus_x, b))
        for y in rows[1:]:
            sch.junction((bus_x, y))
        bus_end = (bus_x, rows[-1] + 2.54)
        sch.wire((bus_x, rows[-1]), bus_end)
        sch.label(f"LED_{L.net_suffix}", bus_end, rot=270)

    sch.text("Each letter: LEDs in parallel from +5V through 1k, switched low-side by its MOSFET.", (bx0, qy - 12.7), size=1.5)
    sch.write(str(out_path))
    return uuids


# --------------------------------------------------------------------------------------
# board
# --------------------------------------------------------------------------------------

BOARD_X0, BOARD_Y0, BOARD_W, BOARD_H, BOARD_R = 50.0, 50.0, 170.0, 52.0, 3.0
CELL = 4.0
TEXT_X0, TEXT_Y0 = 74.0, 59.0     # centre of cell (0,0) of letter 0
LETTER_ADVANCE = 14.0
FET_Y = 82.0
MCU_X, MCU_Y = 144.0, 90.0
TRACK = 0.2
TRACK_POWER = 0.3


def letter_x0(L: Letter) -> float:
    return TEXT_X0 + LETTER_ADVANCE * L.index + (WORD_GAP_AFTER if L.index >= 5 else 0.0)


def cell_center(L: Letter, cell: tuple[int, int]) -> tuple[float, float]:
    c, r = cell
    return (letter_x0(L) + CELL * c, TEXT_Y0 + CELL * r)


def node_of(L: Letter, cell: tuple[int, int]) -> tuple[float, float]:
    """Bottom-right corner node of a cell: where the letter net rails meet."""
    cx, cy = cell_center(L, cell)
    return (cx + CELL / 2, cy + CELL / 2)


STRAIGHT = [(0, -1), (0, 1), (-1, 0), (1, 0)]
DIAGONAL = [(-1, -1), (1, -1), (-1, 1), (1, 1)]

NodeIx = tuple[int, int]   # rail node index: the bottom-right corner of cell (c, r) is node (c + 1, r + 1)


def _unit_segments(path: list[NodeIx]) -> list[tuple[NodeIx, NodeIx]]:
    segs = []
    for a, b in zip(path, path[1:]):
        if a[0] == b[0]:
            step = 1 if b[1] > a[1] else -1
            for j in range(a[1], b[1], step):
                lo, hi = sorted((j, j + step))
                segs.append(((a[0], lo), (a[0], hi)))
        else:
            step = 1 if b[0] > a[0] else -1
            for i in range(a[0], b[0], step):
                lo, hi = sorted((i, i + step))
                segs.append(((lo, a[1]), (hi, a[1])))
    return segs


def _seal_score(path: list[NodeIx], cellset: set[tuple[int, int]]) -> int:
    """How much a rail path seals LED cells off from the +5V pour.

    A rail on a cell's top edge blocks the pour that feeds its anode (3). A rail on a side
    edge narrows the way in (1). A rail on a bottom edge is harmless (0).
    """
    score = 0
    for (i, j), (i2, j2) in _unit_segments(path):
        if j == j2:                      # horizontal unit segment between node columns i..i2 at row j
            if (i, j) in cellset:        # top edge of cell (i, j)
                score += 3
        else:                            # vertical unit segment at node column i between rows j..j2
            if (i - 1, j) in cellset:    # right edge of cell (i-1, j)
                score += 1
            if (i, j) in cellset:        # left edge of cell (i, j)
                score += 1
    return score


def _best_path(na: NodeIx, nb: NodeIx, cellset: set[tuple[int, int]]) -> tuple[int, list[NodeIx]]:
    if na[0] == nb[0] or na[1] == nb[1]:
        p = [na, nb]
        return _seal_score(p, cellset), p
    a = [na, (nb[0], na[1]), nb]   # horizontal first
    b = [na, (na[0], nb[1]), nb]   # vertical first
    sa, sb = _seal_score(a, cellset), _seal_score(b, cellset)
    if sa == sb:
        # tie: put the horizontal leg at the lower row
        return (sa, a) if na[1] >= nb[1] else (sb, b)
    return (sa, a) if sa < sb else (sb, b)


def node_ix(cell: tuple[int, int]) -> NodeIx:
    return (cell[0] + 1, cell[1] + 1)


def letter_rails(cells: list[tuple[int, int]], root: tuple[int, int]) -> list[list[NodeIx]]:
    """Rail paths (in node indices) that join every cell of a letter into one net.

    Straight neighbours are joined first. When a letter falls apart into pieces (the ring
    of an O, the bowls of R and D), the diagonal link with the lowest seal score is added,
    with the better of its two detours.
    """
    cellset = set(cells)
    seen = {root}
    order = [root]
    paths: list[list[NodeIx]] = []
    frontier = [root]
    while True:
        q = deque(frontier)
        while q:
            cur = q.popleft()
            for dc, dr in STRAIGHT:
                nb = (cur[0] + dc, cur[1] + dr)
                if nb in cellset and nb not in seen:
                    seen.add(nb)
                    order.append(nb)
                    paths.append([node_ix(cur), node_ix(nb)])
                    q.append(nb)
        if seen == cellset:
            return paths
        best = None
        for cur in order:
            for dc, dr in DIAGONAL:
                nb = (cur[0] + dc, cur[1] + dr)
                if nb in cellset and nb not in seen:
                    score, path = _best_path(node_ix(cur), node_ix(nb), cellset)
                    if best is None or score < best[0]:
                        best = (score, path, nb)
        assert best, f"letter cells not connected: {cellset - seen}"
        _, path, nb = best
        seen.add(nb)
        order.append(nb)
        paths.append(path)
        frontier = [nb]


def bottom_root(L: Letter) -> tuple[int, int]:
    bottom = [c for c in L.cells if c[1] == 4]
    return min(bottom, key=lambda c: (abs(c[0] - 1), c[0]))


def build_board(out_path: Path, sheetfile: str, ls: list[Letter], netlist: Netlist, sym_uuid: dict[str, str], setup_template: Path | None) -> dict:
    pcb = BoardBuilder(sheetfile=sheetfile, title="HELLO WORLD LED display", date="2026-09-04", rev="v0.1", company="kicad-mcp-layer", setup_template=setup_template)
    pad_net: dict[tuple[str, str], str] = {}
    for net in netlist.nets:
        for node in net.nodes:
            pad_net[(node.ref, node.pin)] = net.name
    comps = {c.ref: c for c in netlist.components}

    def nets_for(ref: str) -> dict[str, str]:
        return {pin: name for (r, pin), name in pad_net.items() if r == ref}

    def place(ref: str, fp: tuple[str, str], at, rot=0.0, *, value_text="", hide_ref=False):
        footprint = load_footprint(*fp)
        comp = comps[ref]
        assert (comp.footprint or fp_id(fp)) == fp_id(fp), (ref, comp.footprint, fp_id(fp))
        # Fields come from the schematic so DRC's parity check sees identical text.
        node = pcb.footprint(
            footprint, ref, comp.value or value_text, at, rot,
            path_uuid=sym_uuid[ref], pad_nets=nets_for(ref), hide_ref=hide_ref,
            description=comp.fields.get("Description", ""), datasheet=comp.fields.get("Datasheet", ""),
        )
        return footprint, node

    x0, y0, x1, y1 = BOARD_X0, BOARD_Y0, BOARD_X0 + BOARD_W, BOARD_Y0 + BOARD_H
    pcb.rounded_rect_outline(x0, y0, x1, y1, BOARD_R)
    inset = 0.5
    pour = [(x0 + inset, y0 + inset), (x1 - inset, y0 + inset), (x1 - inset, y1 - inset), (x0 + inset, y1 - inset)]
    pcb.zone(net="+5V", layer="F.Cu", polygon=pour, name="+5V pour")
    pcb.zone(net="GND", layer="B.Cu", polygon=pour, name="GND pour")

    stats = {"tracks": 0, "vias": 0}

    def track(pts, net, width=TRACK, layer="F.Cu"):
        pcb.track(pts, width=width, layer=layer, net=net)
        stats["tracks"] += len(pts) - 1

    def via(p, net):
        pcb.via(p, net=net)
        stats["vias"] += 1

    # ---- LED matrix ------------------------------------------------------------------
    for L in ls:
        letter_net = f"LED_{L.net_suffix}"
        for cell in L.cells:
            cx, cy = cell_center(L, cell)
            dref, rref = L.led_refs[cell]
            led_fp, _ = place(dref, FP_LED, (cx - 0.9, cy), 90, value_text=LED_VALUE, hide_ref=True)
            r_fp, _ = place(rref, FP_R, (cx + 0.9, cy), 90, value_text=R_LED_VALUE, hide_ref=True)
            k = led_fp.pad_position("1", cx - 0.9, cy, 90)      # cathode, bottom
            r1 = r_fp.pad_position("1", cx + 0.9, cy, 90)       # bottom
            r2 = r_fp.pad_position("2", cx + 0.9, cy, 90)       # top -> letter net
            assert k[1] > cy and r2[1] < cy, (k, r2)
            junction_net = pad_net[(dref, "1")]
            track([k, (r1[0], k[1])], junction_net)
            rail_x = cx + CELL / 2
            track([r2, (rail_x, r2[1]), (rail_x, cy + CELL / 2)], letter_net)
            via((rail_x, cy + CELL / 2), letter_net)   # the letter rails run on the bottom layer
        root = bottom_root(L)
        def node_xy(n: NodeIx) -> tuple[float, float]:
            return (letter_x0(L) + CELL * n[0] - CELL / 2, TEXT_Y0 + CELL * n[1] - CELL / 2)

        for path in letter_rails(L.cells, root):
            track([node_xy(n) for n in path], letter_net, layer="B.Cu")
        # drop to the FET drain
        nx, ny = node_of(L, root)
        fx, fy = nx + 0.9375, FET_Y
        qref = f"Q{L.index + 1}"
        sot, _ = place(qref, FP_SOT23, (fx, fy), 180, value_text="2N7002")
        d = sot.pad_position("3", fx, fy, 180)
        g = sot.pad_position("1", fx, fy, 180)
        s = sot.pad_position("2", fx, fy, 180)
        assert abs(d[0] - nx) < 1e-6 and d[1] == fy, (d, nx)
        track([(nx, ny), d], letter_net)
        via_s = (s[0] + 1.3, s[1])
        track([s, via_s], "GND")
        via(via_s, "GND")
        # gate lane to the MCU
        soic = load_footprint(*FP_SOIC14)
        pin_pos = soic.pad_position(L.mcu_pin, MCU_X, MCU_Y, 0)
        gate_net = f"G_{L.net_suffix}"
        track([g, (g[0], pin_pos[1]), pin_pos], gate_net)
        pcb.text(L.char, (fx + 3.6, fy), size=1.2, thickness=0.2, bold=True)

    # ---- MCU, decoupling, header -----------------------------------------------------
    soic, _ = place("U1", FP_SOIC14, (MCU_X, MCU_Y), 0, value_text="ATtiny1614")
    gnd14 = soic.pad_position("14", MCU_X, MCU_Y, 0)
    via14 = (gnd14[0] + 1.6, gnd14[1])
    track([gnd14, via14], "GND")
    via(via14, "GND")
    updi_pad = soic.pad_position("10", MCU_X, MCU_Y, 0)

    hx, hy = MCU_X, 97.0
    hdr, _ = place("J2", FP_HDR3, (hx - 2.54, hy), 90, value_text="UPDI")
    h1 = hdr.pad_position("1", hx - 2.54, hy, 90)
    h2 = hdr.pad_position("2", hx - 2.54, hy, 90)
    h3 = hdr.pad_position("3", hx - 2.54, hy, 90)
    assert abs(h2[0] - hx) < 1e-6 and abs(h1[1] - hy) < 1e-6, (h1, h2, h3)
    track([h2, (hx, updi_pad[1]), updi_pad], "UPDI")
    via_h3 = (h3[0] + 2.0, h3[1])
    track([h3, via_h3], "GND")
    via(via_h3, "GND")
    pcb.text("UPDI", (hx, hy + 3.8), size=1.0, thickness=0.15)
    pcb.text("5V", (h1[0], hy + 2.3), size=1.0, thickness=0.15)
    pcb.text("GND", (h3[0], hy + 2.3), size=1.0, thickness=0.15)

    c2x, c2y = MCU_X - 9.0, 96.5
    c2, _ = place("C2", FP_C0603, (c2x, c2y), 0, value_text=C_DECOUPLE_VALUE, hide_ref=True)
    c2b = c2.pad_position("2", c2x, c2y, 0)
    via_c2 = (c2b[0] + 1.4, c2b[1])
    track([c2b, via_c2], "GND")
    via(via_c2, "GND")

    # ---- USB-C power entry (left edge, plug facing left) ------------------------------
    ox, oy = 54.15, 86.0
    usb, _ = place("J1", FP_USBC, (ox, oy), 270, value_text="USB-C")
    vbus_lo = usb.pad_position("A4", ox, oy, 270)
    vbus_hi = usb.pad_position("A9", ox, oy, 270)
    gnd_lo = usb.pad_position("A1", ox, oy, 270)
    gnd_hi = usb.pad_position("B1", ox, oy, 270)
    cc1 = usb.pad_position("A5", ox, oy, 270)
    cc2 = usb.pad_position("B5", ox, oy, 270)
    pad_x = vbus_lo[0]
    for vpad in (vbus_lo, vbus_hi):
        away = 1 if vpad[1] > oy else -1          # leave the connector towards the open pour
        track([vpad, (pad_x + 2.3, vpad[1]), (pad_x + 2.3, vpad[1] + 3.6 * away)], "+5V", width=TRACK_POWER)
    for gpad in (gnd_lo, gnd_hi):
        direction = 1 if gpad[1] > oy else -1
        v = (gpad[0], gpad[1] + 1.05 * direction)
        track([gpad, v], "GND", width=TRACK_POWER)
        via(v, "GND")
    # CC pull-downs
    rx = 62.6
    for (ccpad, rref) in ((cc1, "R90"), (cc2, "R91")):
        r, _ = place(rref, FP_R, (rx, ccpad[1]), 0, value_text=R_CC_VALUE, hide_ref=True)
        p1 = r.pad_position("1", rx, ccpad[1], 0)
        p2 = r.pad_position("2", rx, ccpad[1], 0)
        track([ccpad, p1], pad_net[(rref, "1")])
        v = (p2[0] + 1.2, p2[1])
        track([p2, v], "GND")
        via(v, "GND")
    # bulk capacitor
    c1x, c1y = 62.6, oy + 4.6
    c1, _ = place("C1", FP_C0805, (c1x, c1y), 0, value_text=C_BULK_VALUE, hide_ref=True)
    c1b = c1.pad_position("2", c1x, c1y, 0)
    v = (c1b[0] + 1.5, c1b[1])
    track([c1b, v], "GND")
    via(v, "GND")
    pcb.text("USB-C 5V", (61.5, 79.5), size=1.0, thickness=0.15)

    # ---- mounting holes ---------------------------------------------------------------
    for i, (hx_, hy_) in enumerate([(54.5, 54.0), (215.5, 54.0), (215.5, 98.0), (54.5, 98.0)]):
        place(f"H{i + 1}", FP_HOLE, (hx_, hy_), 0, value_text="M3", hide_ref=True)

    # ---- silkscreen -------------------------------------------------------------------
    pcb.text(f"HELLO WORLD  -  {LED_COUNT} LEDs  -  designed by kicad-mcp-layer", (135.0, 54.0), size=1.6, thickness=0.25, bold=True)
    pcb.text("v0.1  2026-09", (208.0, 99.5), size=1.0, thickness=0.15)

    pcb.write(str(out_path))
    return stats
