"""The design package's API sheet: the one file a sheet author reads instead of the source.

``python -m kicad_layer.design.api`` writes ``docs/design-api.md`` from docstrings, signatures,
dataclass fields with their trailing comments, and the catalogue. ``tests/test_design_api.py``
fails when the file is stale, so the sheet is always what the code does.

Why: measured over the first two boards, reading the library's own source to recall its API was
about half of everything the model absorbed. The sheet is a few thousand tokens once per session.
"""

from __future__ import annotations

import importlib
import inspect
import re
import sys
from dataclasses import is_dataclass
from pathlib import Path

DOC_PATH = Path(__file__).resolve().parents[3] / "docs" / "design-api.md"

# (module, title, names) in reading order; None lists every public class and function the module defines
SECTIONS: list[tuple[str, str, list[str] | None]] = [
    ("circuit", "Circuits", ["Circuit", "PartInst", "Pin", "Net"]),
    ("parts", "Parts", ["Part", "Quantity", "verify_all"]),
    ("catalog", "The catalogue", None),
    ("signals", "Signals", ["Signal", "by_sheet", "check_table"]),
    ("render", "Layouts", ["Layout", "At", "Beside", "Decouple", "Flow", "Described", "render"]),
    ("module_sheet", "Module sheets", ["ModuleSheet", "PowerGroup", "DescribedModule"]),
    ("board", "The board", ["Board", "Place", "Header", "Keepout", "Text", "Plane", "check_placement", "build_board"]),
    ("project", "The project", ["Project", "Review", "RootLayout", "Rules", "write_project_file"]),
    ("blocks", "Blocks on a hand-made board", ["Block", "apply", "place"]),
    ("seed", "The first import of a hand-made board", ["Pile", "pack", "seed_board"]),
    ("compare", "Comparing with a reference design, pad for pad", ["compare", "load", "Report", "Row", "Node", "main"]),
    ("copper", "Copper questions: what is there, does a part fit, does a track or via clear", ["Model", "Rules", "Item", "region", "free", "spots", "clear", "clear_via", "load"]),
    ("stubs", "Stub routing of the open connections on single-ended nets", ["route_stubs", "open_connections", "Open", "Result", "main"]),
    ("rules", "Rule sets", ["jlcpcb_4l", "jlcpcb_2l", "aisler_4l", "merge_design_rules", "SILK_WARNINGS", "JLCPCB_2L", "JLCPCB_2L_CLASSES", "STANDARD_CLASSES", "AISLER_CLASSES", "TRACK_WIDTHS", "VIA_DIMENSIONS", "DIFF_PAIR_DIMENSIONS"]),
    ("build", "The build", ["main", "symbol_paths"]),
    ("offline", "Offline builds: the netlist from the descriptions", ["synth_netlist"]),
    ("verify", "Checks with kicad-cli, KiCad closed", ["check_sheet", "check_module", "compare"]),
    ("fab", "Fabrication package", ["main", "pcbway_package"]),
    ("preview", "Previews", None),
    ("gui", "KiCad window control", ["status", "close_kicad", "open_kicad", "lock_files"]),
    ("draw", "Drawing helpers, hand-drawn sheets only", None),
]

HEADER = """# The design package, on one sheet

Generated by `python -m kicad_layer.design.api` from the code; `tests/test_design_api.py` keeps it
current. **Read this, not the source, to write or change a sheet, a board or a project.** Open a
source file only to change the library.

A board is data on `kicad_layer.design`: a signal table, one `Circuit` and one `Layout` per sheet,
a `ModuleSheet` for the module, a `Board` of placements, a `Project`. The build writes the KiCad
files; KiCad's ERC and DRC are the tests. `examples/two_layer_basic` is the smallest complete project on it
(`examples/hello_world` predates the package and drives the writers directly).

## A sheet in twelve lines

```python
from kicad_layer.design.catalog import C_100N, R_10K, IDEAL      # parts, by name, from the catalogue below
from kicad_layer.design.circuit import Circuit
from kicad_layer.design.render import Layout
from signals import by_sheet                                       # the project's signal table

def circuit() -> Circuit:
    c = Circuit("Power", by_sheet("Power"))                        # the signals this sheet must carry
    u4, c23 = c.part("U4", IDEAL), c.part("C23", C_100N)           # u4["3"] is a pin, by number or unique name
    c.signal("USB_EN", u4["3"])                                    # a sheet signal: hierarchical label
    c.rail("+5V", u4["4"])                                         # a power rail: power symbol
    c.gnd(u4["2"], c23["2"])
    c.net(u4["1"], c23["1"])                                       # a private net; name= draws it as local labels
    c.flag("V5_USB")                                               # PWR_FLAG: fed by something ERC cannot see
    c.nc(u4, "7", "8")                                             # pins deliberately open
    return c

LAYOUT = Layout()                                                  # plain: rows, a stub and a label per pin, no lint
```

`Circuit.check()` runs before drawing: every pin on exactly one net or declared open, every signal of
the sheet used, nothing else called a signal. A placed `Layout(parts={...})` follows a plan and is
linted for geometry. A multi-unit symbol is drawn unit by unit: `Layout(parts={"U4": At(...), "U4/B": At(...),
"U4/C": At(...)})` places a dual opamp's units A, B and its power unit (the flow places any left out).

## The loop

```
python <project>/design/build.py --sch-only          # sheets, ERC, netlist and its gates: seconds
python <project>/design/build.py --preview Power     # one PNG per named sheet into _preview/
python <project>/design/build.py --sch-only --review  # plus the pad-for-pad comparison with the project's Review reference
python <project>/design/build.py                     # plus the board and DRC; --reopen / --promote for KiCad
python <project>/design/build.py --route-stubs       # and route what DRC leaves open on single-ended nets, then build again
python <project>/design/build.py --offline           # no kicad-cli (or none found): sheets, project, board on the descriptions' netlist; UNVERIFIED
python -m pytest <project>/tests -q                  # every sheet read back against its description
python -m kicad_layer.design.inspect <build> parts   # questions about a built board: parts, part, net, pin, classes, drc, unrouted, bbox,
                                                     #   region, free, spots, clear, clear-via (copper geometry with the project's clearances)
```

"""


def _first_line(obj) -> str:
    doc = inspect.getdoc(obj) or ""
    return re.sub(r"\s+", " ", doc.split("\n\n")[0]).strip()


def _sig(fn) -> str:
    try:
        s = str(inspect.signature(fn, eval_str=True))
    except Exception:
        try:
            s = str(inspect.signature(fn))
        except (TypeError, ValueError):
            return "(...)"
    s = re.sub(r"(?:kicad_layer\.[\w.]+|typing|collections\.abc|pathlib(?:\._\w+)?)\.(\w+)", r"\1", s)  # short type names (3.13: pathlib._local)
    s = re.sub(r"(?<=: )'([^']+)'|(?<=-> )'([^']+)'", lambda m: m.group(1) or m.group(2), s)  # unevaluated annotations lose their quotes
    s = s.replace("(self, ", "(").replace("(self)", "()")
    return re.sub(r"\s+", " ", s)


def _field_lines(cls) -> list[str]:
    """Dataclass fields from the source, with the trailing comment the code keeps on each line."""
    out = []
    for line in inspect.getsource(cls).splitlines():
        m = re.match(r"^    (\w+): ([^=#]+?)(?: = (.+?))?\s*(?:# (.*))?$", line)
        if not m or m.group(1).startswith("_"):
            continue
        name, typ, default, comment = m.groups()
        default = (default or "").strip()
        if default.startswith("field(default_factory="):
            default = "()" if "tuple" in default or "()" in default else "[]" if "list" in default else "{}" if "dict" in default else "set()" if "set" in default else default
        text = f"- `{name}: {typ.strip()}" + (f" = {default}" if default else "") + "`"
        if comment:
            text += f"  {comment.strip()}"
        out.append(text)
    return out


def _methods(cls) -> list[str]:
    out = []
    for name, member in vars(cls).items():
        if name.startswith("_"):
            continue
        if isinstance(member, property):
            out.append(f"- `.{name}` (property): {_first_line(member.fget)}".rstrip(": "))
        elif inspect.isfunction(member):
            out.append(f"- `{name}{_sig(member)}`: {_first_line(member)}".rstrip(": "))
    return out


def _render_class(cls) -> list[str]:
    out = [f"### {cls.__name__}", ""]
    doc = _first_line(cls)
    if doc and not doc.startswith(cls.__name__ + "("):  # a dataclass without a docstring shows its signature
        out += [doc, ""]
    if is_dataclass(cls):
        out += _field_lines(cls)
    else:
        init = vars(cls).get("__init__")
        if init:
            out.append(f"- `{cls.__name__}{_sig(init)}`")
    out += _methods(cls)
    out.append("")
    return out


def _render_function(fn) -> str:
    return f"- `{fn.__name__}{_sig(fn)}`: {_first_line(fn)}".rstrip(": ")


def _render_catalog(mod) -> list[str]:
    from .parts import Part

    out = ["| name | value | footprint | part | note |", "|---|---|---|---|---|"]
    for name, p in vars(mod).items():
        if isinstance(p, Part) and not name.startswith("_"):
            fp = p.footprint.split(":", 1)[-1]
            note = (p.note[:70] + "...") if len(p.note) > 73 else p.note
            out.append(f"| `{name}` | {p.value} | {fp} | {p.manufacturer} {p.mpn} | {note} |")
    return out + [""]


def generate() -> str:
    out = [HEADER.rstrip("\n"), ""]
    for modname, title, names in SECTIONS:
        mod = importlib.import_module(f"kicad_layer.design.{modname}")
        out += [f"## {title} (`design/{modname}.py`)", ""]
        mdoc = _first_line(mod)
        if mdoc and modname != "catalog":
            out += [mdoc, ""]
        if modname == "catalog":
            out += _render_catalog(mod)
            continue
        if names is None:
            names = [n for n, o in vars(mod).items() if not n.startswith("_") and getattr(o, "__module__", None) == mod.__name__ and (inspect.isclass(o) or inspect.isfunction(o))]
        funcs: list[str] = []
        for name in names:
            obj = getattr(mod, name)
            if inspect.isclass(obj):
                out += _render_class(obj)
            elif inspect.isfunction(obj):
                funcs.append(_render_function(obj))
            else:
                value = re.sub(r"\s+", " ", repr(obj))
                funcs.append(f"- `{name} = {value[:110]}{'...' if len(value) > 110 else ''}`")
        if funcs:
            out += funcs + [""]
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = generate()
    if "--check" in argv:
        current = DOC_PATH.read_text(encoding="utf-8").replace("\r\n", "\n") if DOC_PATH.exists() else ""
        print("current" if current == text else "STALE: run python -m kicad_layer.design.api")
        return 0 if current == text else 1
    DOC_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"{DOC_PATH}: {len(text.splitlines())} lines, about {len(text) // 4} tokens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
